project_id = "glceihfavfvebaaxgsnq"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.save-connection]
verify_jwt = false

[functions.ai-auto-reply]
verify_jwt = false

[functions.execute-flow]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-send]
verify_jwt = false

[functions.ai-flow-selector]
verify_jwt = false

[functions.meta-ad-lookup]
verify_jwt = false

[functions.check-connection-status]
verify_jwt = false

[functions.meta-embedded-signup]
verify_jwt = false

[functions.ai-manager]
verify_jwt = false

[functions.ai-manager-cron]
verify_jwt = false

[functions.ai-follow-up]
verify_jwt = false

[functions.zapi-qrcode]
verify_jwt = false

[functions.exchange-meta-code]
verify_jwt = false